global:
  # SMTP configuration (configure for email alerts)
  smtp_smarthost: 'localhost:587'
  smtp_from: 'tezos-baker@yourdomain.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true

  # Slack configuration (optional)
  slack_api_url: '${SLACK_WEBHOOK_URL}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 24h
  receiver: 'default'
  routes:
    # Critical alerts go to all channels immediately
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 30m
    
    # Warning alerts are grouped and sent less frequently
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 4h

inhibit_rules:
  # Suppress warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'default'
    email_configs:
      - to: '${ALERT_EMAIL}'
        subject: '[Tezos Baker] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: '${ALERT_EMAIL}'
        subject: '🔴 [CRITICAL] Tezos Baker Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>🔴 CRITICAL ALERT</h2>
          <table border="1">
          <tr><th>Alert</th><th>Description</th><th>Instance</th><th>Time</th></tr>
          {{ range .Alerts }}
          <tr>
            <td><strong>{{ .Annotations.summary }}</strong></td>
            <td>{{ .Annotations.description }}</td>
            <td>{{ .Labels.instance }}</td>
            <td>{{ .StartsAt.Format "2006-01-02 15:04:05" }}</td>
          </tr>
          {{ end }}
          </table>
          <p><strong>Immediate action required!</strong></p>
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#tezos-alerts'
        title: '🔴 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}
        color: 'danger'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: '${ALERT_EMAIL}'
        subject: '⚠️ [WARNING] Tezos Baker Alert: {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          {{ end }}
          Please investigate when convenient.

    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#tezos-alerts'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          {{ .Annotations.description }}
          {{ end }}
        color: 'warning'
        send_resolved: true

  # Webhook receiver for custom integrations
  - name: 'webhook'
    webhook_configs:
      - url: 'http://localhost:9093/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook_user'
            password: 'webhook_password'