global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Tezos node metrics
  - job_name: 'tezos-node'
    static_configs:
      - targets: ['tezos-node:9095']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Additional Tezos node RPC-based metrics
  - job_name: 'tezos-node-rpc'
    static_configs:
      - targets: ['tezos-node:8732']
    metrics_path: '/chains/main/blocks/head/header'
    scrape_interval: 60s
    scrape_timeout: 30s
    params:
      format: ['json']

  # Docker container metrics (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    honor_labels: true